config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  devise_for :users
  resources :foods
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    member do
      post 'toggle_public'
    end
    resources :recipe_foods, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  end

  root 'recipes#public_recipes'

  get 'general_shopping_list', to: 'home#shopping_list'
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  belongs_to :user
  has_many :foods, through: :recipe_foods
  has_many :recipe_foods
  belongs_to :user
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    if current_user
      @recipes = current_user.recipes.includes(:recipe_foods).order(created_at: :desc)
    else
      redirect_to new_user_session_path, alert: 'Please log in to view your foods.'
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path, Notice: 'Recipes added successfully'
    else
      flash[:notice] = @recipe.errors.full_messages.join(', ')
      redirect_to request.referrer
    end
  end

  def public_recipes
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_food = @recipe.recipe_foods
  end

  def edit; end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe.recipe_foods.destroy_all
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully deleted.'
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_all_recipes.html.erb
<br/>
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4 p-3" style = "max-width: 300px">
      <%= link_to  recipe_path(recipe) do %>
        <h5><strong></strong><%= recipe.name %></h5>
      <% end %>
      <%= button_to "REMOVE", recipe_path(recipe.id), method: :delete, class:"btn btn-outline-danger"%>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <p class="card-text"><strong>Description: </strong><%= recipe.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>
  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div class="d-flex justify-content-between">
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="card" style="width: 70rem;">
  <div class="card-body">
    <h5 class="card-title"><strong>Recipe: </strong><%= recipe.name %></h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>Preparation time: </strong><%= recipe.preparation_time %></li>
    <li class="list-group-item">  <strong>Cooking time: </strong><%= recipe.cooking_time %></li>
    <li class="list-group-item d-flex"><strong>Public:&nbsp; </strong>
      <%= form_for @recipe, url: toggle_public_recipe_path(@recipe), method: :post, html: { class: "form-inline" } do |form| %>
        <div class="form-check form-switch">
          <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" name="recipe[public]" <%= @recipe.public ? 'checked' : '' %>>
        </div>
        <%= form.submit "Hidden Save", id: "submitButton", style: "display: none" %>
      <% end %>
      <script>
        const checkbox = document.getElementById("flexSwitchCheckChecked");
        const submitButton = document.getElementById("submitButton");

        checkbox.addEventListener("change", function() {
          // Trigger form submission when the checkbox is changed
          if (this.checked === false) {
            submitButton.click(); // Programmatically click the submit button
          }
          if (this.checked === true) {
            submitButton.click(); // Programmatically click the submit button
          }
        window.location.reload()
        });
      </script>
    </li>
  </ul>
  <div class="card-body">
    <p class="card-text"> <strong>Description: </strong><%= recipe.description %></p>
  </div>
  <div class="card-body">
    <%= link_to "Generate Shopping List", new_food_path, class: 'btn btn-outline-dark btn-sm float-start mt-4 mb-4 ml-auto' %>
    <%= link_to "Add Ingredient", new_recipe_recipe_food_path(recipe.id), class: 'btn btn-outline-dark btn-sm float-start mt-4 mb-4 ml-auto' %>
  </div>
</div>
<hr>
<table class="table table-striped ">
  <% if @recipes_food.present? %>
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_food.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td><%= recipe_food.food.price * recipe_food.quantity %></td>
          <td>
            <%= link_to "Modify", recipe_path, method: :get, class: 'btn btn-outline-dark btn-sm float-start'%>
            <%= button_to "Remove", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: 'btn btn-outline-danger btn-sm float-start'%>
          </td>
        </tr>
      <% end%>
    </tbody>
  <% else %>
    <tbody>
      <td>
        <%=  'No foods found please create new food' %>
      </td>
    </tbody>
  <% end %>
</table>

app/views/recipes/index.html.erb
<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render partial: 'recipes/all_recipes', locals: { recipe: recipe } %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center w-50 mt-4">
  <h1>New recipe</h1>
  <%= render "form", recipe: @recipe %>
  <br>
  <div>
    <%= link_to "Back to recipes", recipes_path %>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="users-container">

<div class="public-recipe-container pt-3">
<h1 class='text-center mb-3'>Public Recipes</h1>
  <% @recipes.each do |recipe| %>
    <% unless recipe.public == false %>

    <div class="public-recipe-card card mb-3">
    <div class="row p-3" style="width:100%;">
    <div class="col-md-6">
      <section>
        <%= link_to  recipe_path(recipe) do %>
        <h5><strong></strong><%= recipe.name %></h5>
        <% end %>
        <p class="user-name">By: <%= recipe.user.name %></p>
      </section>
      </div>
      <div class="col-md-6">
      <section>
       
          <p class="user-price-food">Total food items: <%= recipe.recipe_foods.length %></p>
          <% total_price = 0 %>
          <% recipe.recipe_foods.each do |ingredient| %>
            <% total_price += ingredient.quantity * ingredient.food.price %>
          <% end %>
          <p class="user-price-food">Total price: $ <%= total_price %></p>
        </section>
        </div>
        </div>
      </div>
    <% end %>
    <% end %>
  </div>
  </div>

app/views/recipes/show.html.erb
<div class="card mt-5">
  <div class="card-body">
    <h5 class="card-title"><strong>Recipe: </strong><%= @recipe.name %></h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>Preparation time: </strong><%= @recipe.preparation_time %></li>
    <li class="list-group-item">  <strong>Cooking time: </strong><%= @recipe.cooking_time %></li>
    <li class="list-group-item d-flex"><strong>Public:&nbsp; </strong>
    
      <%= form_for @recipe, html: { id: 'recipeForm' } do |f| %>
        <div class="form-check form-switch">
          <%= f.hidden_field :public, value: @recipe.public == false %>
          <%= f.label :public, "Public:", class: "form-check-label" %>
          <%= f.check_box :public, class: "form-check-input", id: "publicSwitch" %>
        </div>
      <% end %>
    </li>
  </ul>
  <div class="card-body">
    <p class="card-text"> <strong>Description: </strong><%= @recipe.description %></p>
  </div>
  <div class="card-body d-flex justify-content-between">
    <%= link_to "Generate Shopping List", general_shopping_list_path, class: 'btn btn-outline-dark btn-sm float-start mt-4 mb-4 ml-auto' %>
    <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-outline-dark btn-sm float-start mt-4 mb-4 ml-auto' %>
  </div>
</div>
<hr>
<table class="table table-striped ">
  <% if @recipe_food.present? %>
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_food.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.quantity %></td>
          <td>$<%= recipe_food.food.price * recipe_food.quantity %></td>
          <td>
            <%= link_to "Modify", edit_recipe_recipe_food_path(@recipe, recipe_food), method: :get, class: 'btn btn-outline-dark btn-sm float-start me-3'%>
            <%= button_to "Remove", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class: 'btn btn-outline-danger btn-sm float-start'%>
          </td>
        </tr>
      <% end%>
    </tbody>
  <% else %>
    <tbody>
      <td>
        <%=  'No foods found please create new food' %>
      </td>
    </tbody>
  <% end %>
</table>


<script>
  document.addEventListener('DOMContentLoaded', function () {
    const publicSwitch = document.getElementById('publicSwitch');
    const form = document.querySelector('#recipeForm');

    publicSwitch.addEventListener('change', function () {
      form.submit();
    });
  });
</script>