config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  devise_for :users
  resources :foods
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    member do
      post 'toggle_public'
    end
    resources :recipe_foods, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  end

  root 'recipes#public_recipes'

  get 'general_shopping_list', to: 'home#shopping_list'
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_foods_helper.rb
module RecipesFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/helpers/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/helpers/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'RecipeApp', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Foods', foods_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Public Recipes", root_path,class: 'nav-link' %>
        </li>
        <% if current_user %>
            <li class="nav-item">
            <%= link_to 'Recipe', recipes_path, class:"nav-link"%>
            </li>

            <li class="nav-item">
              <%= link_to "Create Recipe", new_recipe_path(current_user), class: "nav-link"%>
            </li>
            <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
              <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>