config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  devise_for :users
  resources :foods
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    member do
      post 'toggle_public'
    end
    resources :recipe_foods, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  end

  root 'recipes#public_recipes'

  get 'general_shopping_list', to: 'home#shopping_list'
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :user
  has_many :recipe_foods

  def update_quantity
    total_quantity = recipe_foods.sum(&:quantity)
    update(quantity: total_quantity)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Failed to delete this food item because it is being used by other users.'
  end
  def index
    if current_user
      @foods = current_user.foods.includes(:recipe_foods).order(created_at: :desc)
    else

      redirect_to new_user_session_path, alert: 'Please log in to view your foods.'
    end
  end

  def create
    @food = current_user.foods.new(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food added successfully'
    else
      render 'new', notice: 'Error adding Food'
    end
  end

  def new
    @food = Food.new
  end

  def destroy
    @food = Food.find(params[:id])
    @food.recipe_foods.destroy_all
    if @food.destroy
      redirect_to foods_path, notice: 'Food deleted successfully'
    else
      redirect_to foods_path, alert: 'Error deleting Food'
    end
  end

  def food_params
    params.require(:food).permit(:name, :quantity, :measurement_unit, :price)
  end
end

# class FoodsController < ApplicationController
#   load_and_authorize_resource
#   rescue_from CanCan::AccessDenied do |_exception|
#     redirect_to root_path, notice: 'Failed to delete this food item because it is being used by other users.'
#   end
#   def index
#     if current_user
#       @foods = current_user.foods.includes(:recipe_foods).order(created_at: :desc)
#     else

#       redirect_to new_user_session_path, alert: 'Please log in to view your foods.'
#     end
#   end

#   def create
#     @food = current_user.foods.new(food_params)
#     if @food.save
#       redirect_to foods_path, notice: 'Food added successfully'
#     else
#       render 'new', notice: 'Error adding Food'
#     end
#   end

#   def new
#     @food = Food.new
#   end

#   def destroy
#     @food = Food.find(params[:id])
#     @food.recipe_foods.destroy_all
#     if @food.destroy
#       redirect_to foods_path, notice: 'Food deleted successfully'
#     else
#       redirect_to foods_path, alert: 'Error deleting Food'
#     end
#   end

#   def food_params
#     params.require(:food).permit(:name, :quantity, :measurement_unit, :price)
#   end
# end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>
  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<br>
<table class="table table-striped table-bordered">
  <thead class= "table-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Unit price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td>$ <%= food.price %></td>
        <td><%= button_to "Delete", food, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New food", new_food_path, class:"btn btn-dark"%>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>