config/routes.rb
Rails.application.routes.draw do
  resources :recipe_foods
  devise_for :users
  resources :foods
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    member do
      post 'toggle_public'
    end
    resources :recipe_foods, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  end

  root 'recipes#public_recipes'

  get 'general_shopping_list', to: 'home#shopping_list'
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :recipe
  belongs_to :food
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where.not(id: RecipeFood.where(recipe_id: @recipe.id).pluck(:food_id))

    @recipe_food = RecipeFood.new
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe = Recipe.find(@recipe_food.recipe_id)

    if @recipe_food.save
      flash[:notice] = 'Ingredient added!'
      # Update the associated food's quantity.
      @recipe_food.food.update_quantity
    else
      flash[:alert] = @recipe_food.errors.full_messages.join(', ')
    end

    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])

    flash[:notice] = if @recipe_food.destroy
                       'Ingredient Removed!'
                     else
                       @recipe_food.errors.full_messages.join(', ')
                     end
    @recipe_food.food.update_quantity
    redirect_to request.referrer
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])

    if @recipe_food.update(quantity_param)
      flash[:notice] = 'Ingredient updated!'
      @recipe_food.food.update_quantity
      redirect_to recipe_path(params[:recipe_id])
    else
      flash[:notice] = @recipe_food.errors.full_messages.join(', ')
      redirect_to request.referrer
    end
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :recipe_id, :quantity)
  end

  def quantity_param
    params.require(:recipe_food).permit(:quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :recipe_id, style: "display: block" %>
    <%= form.text_field :recipe_id %>
  </div>

  <div>
    <%= form.label :food_id, style: "display: block" %>
    <%= form.text_field :food_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

  <p>
    <strong>Recipe:</strong>
    <%= recipe_food.recipe_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food_id %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<p class="page-title">Edit Ingredient</p>
<div class="foods-container">
  <table>
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Unit Price</th>
      <th>Actions</th>
    </tr>
    <tr>
      <td><%= @recipe_food.food.name %></td>
      <td><%= @recipe_food.food.measurement_unit %></td>
      <td>$ <%= @recipe_food.food.price %></td>
      <td>
        <%= form_with model: @recipe_food, url: recipe_recipe_food_path(@recipe,@recipe_food)  do |f| %>
          <%= f.number_field :quantity, value: @recipe_food.quantity %>
          <%= f.submit "Modify" %>
        <% end %>
      </td>
    </tr>
  </table>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1>Add ingredients</h1>
<h1><%=@recipe.name%></h1>
<p class="page-title">Add new ingredients</p>
<div class="foods-container">
  <table class="table table-striped table-bordered">
    <thead class= "table-dark">
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Unit Price</th>
      <th>Actions</th>
    </tr>
    </thead>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td>$ <%= food.price %></td>
        <td>
        <%= form_with model: @recipe_food, url: recipe_recipe_foods_path(@recipe) do |f| %>
          <%= f.hidden_field :recipe_id, value: @recipe.id %>
          <%= f.hidden_field :food_id, value: food.id %>
          <%= f.number_field :quantity, value: 0 %>
          <%= f.submit "Add" %>
        <% end %>        
        </td>
      </tr>
    <% end %>
  </table>
</div>